baseURL = 'https://nathan.leclercq.spacesheep.ovh/'
languageCode = 'fr-fr'
title = 'Nathan Leclercq'
theme = "hermit-v2"

pygmentsCodefences  = true
pygmentsUseClasses  = true

rssLimit = 10

copyright = "Tous droits réservés."
enableEmoji = true

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

[params.author]
  name = "Nathan Leclercq"
  about = ""

[taxonomies]
  tag = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  description = "Portfolio de Nathan Leclercq."
  images = ["https://i.ibb.co/sH6V9M4/spacesheep-1.jpg", "https://i.ibb.co/CJTPv1Y/spacesheep-2.png"]
  themeColor = "#494f5c"

  homeSubtitle = "Portfolio de Nathan Leclercq."
  footerCopyright = "Tous droits réservés"
  footerHideThemeName = true
  bgImg = "https://i.ibb.co/sH6V9M4/spacesheep-1.jpg"

  justifyContent = false

  relatedPosts = true
  code_copy_button = true

  homeSubtitlePrinter = true
  scrollToTop = true
  global_mathjax = false
  readTime = true
  readTimeSeparator = "minutes de lecture"
  shareSocial = false
  allowRobots = "index, follow"
  noIndexPages = ["404 Page not found"]

  [[params.socialLinks]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/nathan-leclercq-51292014b/"

  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/nathanlq"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "À propos"
    url = "about"
    weight = 20

  [[menu.main]]
    name = "Curriculum Vitae"
    url = "cv_fr"
    weight = 30

  [[menu.main]]
    name = "Resume"
    url = "cv_en"
    weight = 30

